openapi: 3.1.0
info:
  title: FirstQuadrant API
  description: The FirstQuadrant API is used to interact with FirstQuadrant programmatically.
  termsOfService: https://firstquadrant.ai/terms
  contact:
    email: inquiry@firstquadrant.ai
  version: 0.0.0
servers:
  - url: https://firstquadrant.ai
tags:
  - name: teams
    description: Operations about your team
  - name: conversations
    description: Inform FirstQuadrant about events using incoming webhooks
paths:
  /api/teams/me:
    get:
      tags:
        - teams
      description: Get the team associated with the API key.
      security:
        - api_key:
            - read:team
  /api/teams/{teamId}:
    get:
      tags:
        - teams
      description: Get a team by ID.
      security:
        - api_key:
            - read:team
    patch:
      tags:
        - teams
      description: Update a team by ID.
      security:
        - api_key:
            - write:team
    delete:
      tags:
        - teams
      description: Delete a team by ID.
      security:
        - sudo:
            - write:*
  /api/teams/{teamId}/outbound:
    get:
      tags:
        - teams
      description: Get the outbound settings for a team by ID.
      security:
        - api_key:
            - read:team
    patch:
      tags:
        - teams
      description: Update the outbound settings for a team by ID.
      security:
        - api_key:
            - read:team
  /api/teams/{teamId}/contacts:
    get:
      tags:
        - teams
      description: Get all contacts for a team.
      security:
        - api_key:
            - read:team
  /api/teams/{teamId}/contacts/{contactId}:
    get:
      tags:
        - teams
      description: Get a contact by ID.
      security:
        - api_key:
            - read:team
    patch:
      tags:
        - teams
      description: Update a contact by ID.
      security:
        - api_key:
            - read:team
    delete:
      tags:
        - teams
      description: Delete a contact by ID.
      security:
        - api_key:
            - read:team
  /api/teams/{teamId}/contacts/{contactId}/block:
    post:
      tags:
        - teams
      description: Unsubscribe a contact by ID.
      security:
        - api_key:
            - read:team
  /api/teams/{teamId}/contacts/{contactId}/unblock:
    post:
      tags:
        - teams
      description: Resubscribe an unsubscribed a contact by ID.
      security:
        - api_key:
            - read:team
  /api/teams/{teamId}/contacts/{contactId}/campaign-contacts:
    get:
      tags:
        - teams
      description: Get all campaign contacts for a contacts.
      security:
        - api_key:
            - read:team
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Bearer API key
      description: The API key used to authenticate requests, learn how to generate an API key on the [Authentication](https://docs.firstquadrant.ai/api-reference/authentication) page.
    sudo:
      type: apiKey
      in: header
      name: Superuser access
      description: This header is used to authenticate as a superuser. Your API key must have the `sudo` scope to use this header.
